### ISSUE TITLE
Add pagination to all scrapers where possible

### ISSUE THREAD

**Issue by caffeinatedMike** [caffeinatedMike/plugin.video.Squeee#4]
Collect links from default or user-defined number of pages for every scraper where possible. Some scrapers, due to dynamic loading, will not be able to have multi-page scraping. Need to define a property for all scraper classes that will indicate if they can be paginated.

**Comment by caffeinatedMike** [comment]
Also, will want to add option to set how many items to display per page and have a `NEXT PAGE >` listitem as the last item in the directory, leading to the next set of x videos.

**Comment by caffeinatedMike** [comment]
To continue adding helpful information for when this issue is started, in order to speed up the process of the scraping threading should be implemented just as it is in [scraper.py](https://github.com/caffeinatedMike/plugin.video.Squeee/blob/b07cd41/resources/lib/sources/scraper.py#17) lines 17-19.

**Comment by inspector71** [comment]
none of that code makes much sense to me. Not your code style or choices,
just the bloody python. 🙁

Looks like a language with almost no meaning except to remove punctuation
and squeeze every action on to one line.

Garrrgh!

**Comment by caffeinatedMike** [comment]
Hey, no worries. We're all here to learn :)

```
pool = ThreadPoolExecutor(len(self.sources))
futures = [pool.submit(self.thread, source) for source in self.sources]
[self.links.extend(r.result()) for r in as_completed(futures)]
```
Here's a little crash course of what those lines of code are doing. The code appears compact because it is, but it's also written this way for efficiency (uses list generators `[ ]`, which use less memory & process faster than `for` loops)

`pool = ThreadPoolExecutor(len(self.sources))`
This line is setting the number of concurrent threads that we will be using. Meaning, we're telling the program that we are going to be doing x processes at the same time. The reason for doing this is to only allocate the necessary number of resources needed instead of using more resources than are necessary, leading to performance hits.

`futures = [pool.submit(self.thread, source) for source in self.sources]`
`pool.submit` is sending each process to its own thread and has it start running.
`for source in self.sources` is saying that we're starting one thread for each source.

`[self.links.extend(r.result()) for r in as_completed(futures)]`
`r.result()` is going to be a comma-separated list of results from a scraper. Since all source scrapers return tuples (eg `[(imagelink1, title1, videolink1), (imagelink2, title2, videolink2), (imagelink3, title3, videolink3)]` ) `r.result()` will be those tuples.
`.extend()` is a list function that allows adding multiple values to a list at once. Think of `.extend()` as a supercharged version of `.append()`, which allows adding a single value to the end of a list. 

`for r in as_completed(futures)`
`as_completed` is saying as each source/thread completes process it and append the results to the `self.links` list, which is the list of links that will be returned after all is said and done.

Does that help shed any light on things?

**Comment by caffeinatedMike** [comment]
Setting added in above merged pull request that allows user to set number of links to show per page (for their preference and for performance tweaking ie showing less to load faster). When implementing pagination, however we do it, check this setting to show the appropriate number of links per page.

**Comment by caffeinatedMike** [comment]
Was just thinking, this will be tough to implement in `By Category` & `By Animal` sections since they both involve scraping multiple links. In order to implement this correctly (hopefully) without hinderance on performance we should consider implementing [pickling](http://www.pitt.edu/~naraehan/python2/pickling.html)

**Comment by caffeinatedMike** [comment]
**Still thinking out load:**
Seems like the best place to implement the core of the pagination will be in the `schema.py` functions
```
    def get_listing(self, source, page=1):
        import importlib
        if '[' in source: #Remove Status Label
            source = source[:source.find('[')].lower()
        source = importlib.import_module('.'+source, package='resources.lib.sources')
        links = source.Site().scrape()
        for i, (title, image, link) in enumerate(links):
            list_item = xbmcgui.ListItem(label=title)
            list_item.setProperty('IsPlayable','true')
            list_item.setArt({'poster': image, 'banner': image})
            url = get_url(action='play', video=link)
            xbmcplugin.addDirectoryItem(data._handle, url, list_item, False)
        list_item = xbmcgui.ListItem(label='NEXT PAGE >>>')
        #list_item.setArt({'poster': image, 'banner': image})
        url = get_url(action='listing', source=source, page=page+1)
        xbmcplugin.addDirectoryItem(data._handle, url, list_item, False)
        xbmcplugin.addSortMethod(data._handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
        xbmcplugin.endOfDirectory(data._handle)
    
    def get_category(self, category, page=1):
        cat = meta().has_category(category)
        import importlib
        for source in cat:
            source = importlib.import_module('.'+source, package='resources.lib.sources')
            links = source.Site().scrape()
            for i, (title, image, link) in enumerate(links):
                list_item = xbmcgui.ListItem(label=title)
                list_item.setProperty('IsPlayable','true')
                list_item.setArt({'poster': image, 'banner': image})
                url = get_url(action='play', video=link)
                xbmcplugin.addDirectoryItem(data._handle, url, list_item, False)
        list_item = xbmcgui.ListItem(label='NEXT PAGE >>>')
        #list_item.setArt({'poster': image, 'banner': image})
        url = get_url(action='listing', source=source, page=page+1)
        xbmcplugin.addDirectoryItem(data._handle, url, list_item, False)
        xbmcplugin.addSortMethod(data._handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
        xbmcplugin.endOfDirectory(data._handle)
    
    def get_animal(self, animal, page=1):
        sources = meta().has_animal(animal)
        print sources
        import importlib
        for source in sources:
            source = importlib.import_module('.'+source, package='resources.lib.sources')
            links = source.Site().scrape()
            for i, (title, image, link) in enumerate(links):
                list_item = xbmcgui.ListItem(label=title)
                list_item.setProperty('IsPlayable','true')
                list_item.setArt({'poster': image, 'banner': image})
                url = get_url(action='play', video=link)
                xbmcplugin.addDirectoryItem(data._handle, url, list_item, False)
        list_item = xbmcgui.ListItem(label='NEXT PAGE >>>')
        #list_item.setArt({'poster': image, 'banner': image})
        url = get_url(action='listing', source=source, page=page+1)
        xbmcplugin.addDirectoryItem(data._handle, url, list_item, False)
        xbmcplugin.addSortMethod(data._handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_THE)
        xbmcplugin.endOfDirectory(data._handle)
```

**Comment by caffeinatedMike** [comment]
Sources that are currently being implemented on [pagination-feature](https://github.com/caffeinatedMike/plugin.video.Squeee/tree/pagination-feature) branch:
 - [x] dogwork.py
 - [x] dailyhaha.py
 - [x] funnyanimal.py
 - [x] funnyanimalvideos.py
 - [x] funnycatsite.py
 - [x] funnydogsite.py
 - [x] justcatvideos.py
 - [x] justdogvideos.py
 - [x] myfunnycatvideos.py

Problematic sources that will need to vary from generic pagination implementation:
- [ ] redditcatvideos.py
- [ ] thepetcollective.py
- [ ] zooborns.py

Special case that needs to be looked at separately
 - [ ] explore.py (live source)
