### ISSUE TITLE
Proposal for menu layout

### ISSUE THREAD

**Issue by JohnIIDX** [caffeinatedMike/plugin.video.Squeee#41]
- Categories
      - Cute/Funny
      - Safari/Outdoor
      - Random

- Animals
      - Cats
      - Dogs
      - Etc.
      - Random

- Sites
      - Dailyhaha
      - Funnycatsite
      - Etc.
      - Random
-All
-Random (continuous play)

This does not include the live streams and is only meant to be used as a skeleton to build the menu.  Please add to this as necessary.

**Comment by caffeinatedMike** [comment]
Closing as duplicate of #40
